# Generated by Django 4.1.1 on 2022-10-11 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL, verbose_name='Post likes'),
        ),
    ]
