# Generated by Django 4.1.1 on 2022-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapost',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=100, verbose_name='color ategory'),
        ),
    ]
