# Generated by Django 4.1.1 on 2022-10-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
