# Generated by Django 4.1.1 on 2022-10-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
