# Generated by Django 4.1.1 on 2022-10-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment_approved_comment_comment_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
