# Generated by Django 4.1.1 on 2022-10-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
