# Generated by Django 4.1.1 on 2022-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_comment_options_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.CharField(max_length=255),
        ),
    ]
