# Generated by Django 4.1.1 on 2022-10-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_comment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
