# Generated by Django 4.1.1 on 2022-10-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_src',
            field=models.URLField(default='http://127.0.0.1:8000/<django.db.models.fields.files.FileField>', verbose_name='post image source '),
        ),
    ]
